on: [push, pull_request]
name: CI
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
    # Prepare
    - name: Install Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Export GOPATH
      run: echo "::set-env name=GOPATH::$(go env GOPATH)"
    - name: Append GOPATH onto PATH
      run: echo "::set-env name=PATH::$PATH:$GOPATH/bin"

    # TESTS

    # Run all tests
    - name: Test
      run: go test -v ./...

    # LINT

    # Install golint
    - name: Install golint
      run: go get golang.org/x/lint/golint

    # Install golangci-lint
    - name: Install golangci-lint
      run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6

    # go vet
    - name: go vet
      run: go vet ./...

    # golangci-lint
    - name: golangci-lint
      run: golangci-lint run ./...

    # golint
    - name: golint
      run: golint -set_exit_status $(go list ./...)
